### ISSUE TITLE
Request to add Talisman under the "Wallet" category.

### ISSUE THREAD

**Issue by anaelleltd** [Awesomedot/awesome-dot#2]
Namaste aap log,

I just saw this github on Kusamassembly. What a fantastic idea! 💯 
I'm here with a request.

[Talisman dapp](https://app.talisman.xyz/) is currently the only platform in the Polkadot/Kusama ecosystem that offers users unique branding, fiat on-ramp purchasing, seamless crowdloaning, and cross-chain balance viewing across all accounts. 

The Talisman browser extension will release at the end of this month.
Can I request that you add their app to your list of wallets, please?

Bahut shukria! :)

Ps: You can also help contribute to the dapp with translations (Hindi, Urdu, Bengali, Marathi, Gujrati, etc.) through [PR](https://github.com/TalismanSociety/talisman-web/tree/prod/public/locales)s. 🥇

**Comment by itssravi** [comment]
Dhanyawad aapka,

Thank you so much for your inputs. Please ping if you want to add anything. I will be really happy to add to this list.
